### ISSUE TITLE
你好文档有更新，Date: 16 Jul 2017

### ISSUE THREAD

**Issue by sxdubin** [toyjack/phpdoc-zh-docset#2]
你好，php手册 官网的最新版是：Date: 16 Jul 2017，能不能更新至最新版，谢谢。

**Comment by toyjack** [comment]
你好，感谢留言。抱歉回复的晚了。
官网手册的那个日期应该是指手册文件生成的日期，
对应到现在的稳定版7.17。
而本文档虽然近半年没有更新，
但是对应到7.1版本。
在PHP更新到7.2之前没有更新计划，不好意思。
